[en]
  languageName = "English"
  languageCode = "en-US"
  weight = 10
  [en.params]
    languageISO = "EN"

[de]
  languageName = "German"
  languageCode = "de-CH"
  weight = 20
  [de.params]
    languageISO = "DE"

[fr]
  languageName = "French"
  languageCode = "fr-CH"
  weight = 30
  [fr.params]
    languageISO = "FR"

[it]
  languageName = "Italian"
  languageCode = "it-CH"
  weight = 40
  [it.params]
    languageISO = "IT"
