[[main]]
name = "Perché noi?"
url = "#features"
weight = 10

[[main]]
identifier = "servizi"
name = "Servizi"
url = "#testimonials"
weight = 20

[[main]]
name = "Sviluppo su misura"
url = "sviluppo/"
weight = 10
parent = "servizi"
params.icon = "bi bi-code-slash"

[[main]]
identifier = "servizi-supporto-manutenzione"
name = "Supporto e manutenzione QGIS"
url = "supporto-qgis/"
weight = 20
parent = "servizi"
params.icon = "bi bi-tools"

[[main]]
name = "La nostra iniziativa di sostenibilità QGIS"
url = "la-nostra-iniziativa-di-sostenibilita-qgis/"
weight = 30
parent = "servizi-supporto-manutenzione"
params.icon = "bi bi-emoji-smile"

[[main]]
identifier = "servizi-consulenza"
name = "Consulenza"
url = "consulenza/"
weight = 40
parent = "servizi"
params.icon = "bi bi-rocket"

[[main]]
name = "Servizi di consulenza"
url = "consulenza/"
weight = 45
parent = "servizi-consulenza"
params.icon = "obfx-menu-icon fa fa-handshake-o"

[[main]]
name = "Pacchetti di avvio a QField"
url = "qfield-training/"
weight = 50
parent = "servizi-consulenza"
params.icon = "bi bi-phone"

[[main]]
identifier = "servizi-corsi"
name = "Corsi"
url = "category/corsi/"
weight = 60
parent = "servizi"
params.icon = "bi bi-mortarboard"

[[main]]
name = "Calendario dei corsi"
url = "calendario-corsi/"
weight = 70
parent = "servizi-corsi"
params.icon = "bi bi-calendar3"

[[main]]
name = "Iscrizione corsi"
url = "iscrizione-corsi/"
weight = 80
parent = "servizi-corsi"
params.icon = "bi bi-pencil-square"

[[main]]
name = "Corsi QGIS"
url = "category/corsi/corsi-qgis/"
weight = 90
parent = "servizi-corsi"
params.icon = "bi bi-display"

[[main]]
name = "Corsi QField"
url = "category/corsi/corsi-qfield/"
weight = 100
parent = "servizi-corsi"
params.icon = "bi bi-phone"

[[main]]
name = "Corsi INTERLIS & Model Baker"
url = "category/corsi/corsi-interlis-model-baker/"
weight = 110
parent = "servizi-corsi"
params.icon = "bi bi-diagram-3"

[[main]]
name = "corsi PostGIS"
url = "category/corsi/corsi-postgis/"
weight = 120
parent = "servizi-corsi"
params.icon = "bi bi-database"

[[main]]
name = "Corsi PyQGIS"
url = "category/corsi/corsi-pyqgis/"
weight = 130
parent = "servizi-corsi"
params.icon = "bi bi-file-earmark-code"

[[main]]
identifier = "noi"
name = "Noi"
url = "#team"
weight = 30

[[main]]
name = "Team"
url = "#team"
weight = 10
parent = "noi"
params.icon = "bi bi-people"

[[main]]
name = "Jobs"
url = "jobs/"
weight = 20
parent = "noi"
params.icon = "bi bi-rocket"

[[main]]
name = "I nostri valori"
url = "i-nostri-valori/"
weight = 30
parent = "noi"
params.icon = "bi bi-heart"

[[main]]
identifier = "qfield"
name = "QField"
url = "https://qfield.org/"
weight = 40

[[main]]
name = "qfield.org"
url = "https://qfield.org/"
weight = 10
parent = "qfield"
params.icon = "bi bi-phone"

[[main]]
name = "QFieldCloud"
url = "https://qfield.cloud/"
weight = 20
parent = "qfield"
params.icon = "bi bi-cloud"

[[main]]
name = "Pacchetti di avvio a QField"
url = "qfield-training/"
weight = 30
parent = "qfield"
params.icon = "bi bi-mortarboard"

[[main]]
name = "Novità"
url = "category/qfield-it/highlights/"
weight = 40
parent = "qfield"
params.icon = "bi bi-star-fill"

[[main]]
name = "Contatto"
url = "#contact"
weight = 50

[[main]]
name = "Blog"
url = "blog/"
weight = 60
