[[main]]
name = "Why us?"
url = "#features"
weight = 10

[[main]]
identifier = "services"
name = "Services"
url = "#testimonials"
weight = 20

[[main]]
name = "Custom Development"
url = "custom-development/"
weight = 10
parent = "services"
params.icon = "bi bi-code-slash"

[[main]]
identifier = "services-support-maintenance"
name = "Support & maintenance"
url = "qgis-support/"
weight = 20
parent = "services"
params.icon = "bi bi-tools"

[[main]]
name = "Support contracts"
url = "qgis-support/"
weight = 30
parent = "services-support-maintenance"
params.icon = "bi bi-headset"

[[main]]
name = "QGIS Sustainability initiative"
url = "qgis-sustainability-initiative/"
weight = 40
parent = "services-support-maintenance"
params.icon = "bi bi-emoji-smile"

[[main]]
identifier = "services-consulting"
name = "Consulting"
url = "training-consulting/"
weight = 50
parent = "services"
params.icon = "bi bi-rocket"

[[main]]
name = "Consulting services"
url = "training-consulting/"
weight = 55
parent = "services-consulting"
params.icon = "obfx-menu-icon fa fa-handshake-o"

[[main]]
name = "QField Jump-start packages"
url = "qfield-training/"
weight = 60
parent = "services-consulting"
params.icon = "bi bi-phone"

[[main]]
identifier = "services-courses"
name = "Courses"
url = "category/courses/"
weight = 70
parent = "services"
params.icon = "bi bi-mortarboard"

[[main]]
name = "Courses calendar"
url = "courses-calendar/"
weight = 80
parent = "services-courses"
params.icon = "bi bi-calendar3"

[[main]]
name = "Course registration"
url = "course-registration/"
weight = 90
parent = "services-courses"
params.icon = "bi bi-pencil-square"

[[main]]
name = "QGIS courses"
url = "category/courses/qgis-courses/"
weight = 100
parent = "services-courses"
params.icon = "bi bi-display"

[[main]]
name = "QField courses"
url = "category/courses/qfield-courses/"
weight = 110
parent = "services-courses"
params.icon = "bi bi-phone"

[[main]]
name = "INTERLIS & Model Baker courses"
url = "category/courses/interlis-model-baker-courses/"
weight = 120
parent = "services-courses"
params.icon = "bi bi-diagram-3"

[[main]]
name = "PostGIS courses"
url = "category/courses/postgis-courses/"
weight = 130
parent = "services-courses"
params.icon = "bi bi-database"

[[main]]
name = "PyQGIS courses"
url = "category/courses/pyqgis-courses/"
weight = 140
parent = "services-courses"
params.icon = "bi bi-file-earmark-code"

[[main]]
identifier = "about"
name = "About"
url = "#team"
weight = 30

[[main]]
name = "Team"
url = "#team"
weight = 10
parent = "about"
params.icon = "bi bi-people"

[[main]]
name = "Our core values"
url = "core-values/"
weight = 20
parent = "about"
params.icon = "bi bi-heart"

[[main]]
name = "Join Us"
url = "jobs/"
weight = 30
parent = "about"
params.icon = "bi bi-rocket"

[[main]]
identifier = "qfield"
name = "QField"
url = "https://qfield.org/"
weight = 40

[[main]]
name = "qfield.org"
url = "https://qfield.org/"
weight = 10
parent = "qfield"
params.icon = "bi bi-phone"

[[main]]
name = "QFieldCloud"
url = "https://qfield.cloud/"
weight = 20
parent = "qfield"
params.icon = "bi bi-cloud"

[[main]]
name = "Jump-start packages"
url = "qfield-training/"
weight = 30
parent = "qfield"
params.icon = "bi bi-mortarboard"

[[main]]
name = "Highlights"
url = "category/qfield/highlights/"
weight = 40
parent = "qfield"
params.icon = "bi bi-star-fill"

[[main]]
name = "Blog"
url = "blog/"
weight = 50

[[main]]
name = "Contact"
url = "#contact"
weight = 60
